//! Aqueduct-LOA — the typed completeness-refusal core.
//!
//! SPECIMEN, not wired code. Generated by claude-web 2026-06-25; preserved here as a
//! runtime/Rust PROJECTION of LeanProofs/Scratch/PredicateWitnessSeparation.lean
//! (coherence-under-translation by the same doctrine-carrying author — NOT independent
//! rediscovery; see companion note §provenance). Compiles
//! clean as shipped (rustc 1.94, --edition 2021); uncommenting `is_cleared` at the bottom
//! reproduces error[E0369] — that failure-to-compile IS the No-Silent-Conversion proof.
//! See companion note: aqueduct-loa-rust-specimen.md. Not part of any build; illustrative.
//!
//! SCOPE OF THIS FILE: only "step 6" — the boundary-as-typed-refusal object and
//! the downstream check that refuses on out-of-boundary. Steps 1–5 (generate the
//! SBOM, run the license scanner, collect SLSA provenance, resolve the dependency
//! graph) are plumbing and are deliberately absent. They are what *produces* the
//! `Coverage` this code consumes. The doctrine lives here, not in the plumbing.
//!
//! DOCTRINAL MAPPING — each property is enforced by a type, not a comment:
//!
//!   signed is not witnessed
//!       `verify_binding`: a signed attestation whose subject digest != the
//!       artifact actually in hand witnesses nothing about that artifact. The
//!       resolver refuses before reading any verdict.
//!
//!   No Negative Clearance
//!       A whole-artifact clearance cannot be derived from "everything I examined
//!       passed." That is clearance-from-absence-of-findings. It requires a
//!       `ClosureWitness` proving the examined set is complete relative to the
//!       artifact. Absent that witness, the completeness claim is `Refused` —
//!       never `Admissible`. The sentence "this attestation does not prove
//!       absence outside boundary B" is the variant `RefusalReason::NoClosureWitness`.
//!
//!   No Silent Conversion
//!       `Resolution` is a three-valued sum with no `Default`, no `PartialEq`
//!       (so you cannot `== Admissible` your way to a bool), no `From<Resolution>
//!       for bool`, and it is `#[must_use]`. To ACT past a refusal you must
//!       construct a `RefusalOverride` carrying a signer and a justification, and
//!       route through `decide`, whose type cannot turn `Refused` into `Proceed`.
//!       Proceeding despite a refusal is therefore a recorded act, not a fall-through,
//!       and it is a *different fact* from "it was clear."
//!
//! WHAT THIS FILE DOES NOT ENFORCE (stated honestly): it enforces "no silent
//! conversion of refusal into clearance." It does NOT enforce that the gate is
//! actually on the execution path — that the consumer calls `decide` at all.
//! Liveness ("the admissibility gate is invoked before use") is a separate seam,
//! the job of the harness that wraps execution (Wicket proper), not of these types.

#![allow(dead_code)] // several fields are structurally meaningful but unread by the demo

use std::collections::BTreeMap;

// ---------------------------------------------------------------------------
// identities — newtypes so an artifact digest cannot be silently used as a
// policy digest, and a component id cannot be used as either.
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Debug)]
struct Sha256(String);

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
struct ComponentId(String); // think purl, e.g. "pkg:cargo/serde@1.0.197"

#[derive(Clone, Debug)]
struct Signer(String);

// ---------------------------------------------------------------------------
// coverage — the witnessed region. The KEYS of `examined` ARE the boundary B.
// There is deliberately no "assumed clear" entry. A component is either examined
// (and carries a verdict) or it is outside B. Outside-B is not stored as data —
// its sole representation is the *refusal* the resolver returns. Absence here is
// never clearance; it is the precondition for refusal.
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Verdict {
    Pass,
    Fail,
}

struct Coverage {
    examined: BTreeMap<ComponentId, Verdict>,
}

/// A license/origin attestation, bound to exactly one artifact digest.
/// (Evidence digests — SBOM, provenance, scan-result hashes — would live here and
/// be re-checked; elided to keep the doctrinal core legible.)
struct LicenseOriginAttestation {
    subject: Sha256,
    policy: Sha256,
    coverage: Coverage,
    signer: Signer,
}

// ---------------------------------------------------------------------------
// closure witness — the ONLY thing that can license a completeness claim.
//
// It attests: boundary B is complete relative to the artifact, i.e. the examined
// set ⊇ the artifact's actual license-bearing component set. This is the hard
// claim, because it is a NEGATIVE: "there is no undeclared upstream." A negative
// is only sound under a closed-world basis — hermetic build, complete material
// capture, declared scanner coverage, snippet-detection assumptions, generated-
// code rules. We MODEL the witness. We pointedly do not fabricate one. The
// specimen ships without a valid witness, so whole-artifact clearance is
// structurally `Refused`.
//
// CAVEAT (companion-note §turtle): constructing a ClosureWitness is itself a
// `signed != witnessed` act — `builder_digest` is never checked, `basis` is
// unverified. The witness is ADMITTED, not VERIFIED, here. Whether the witness is
// real is the next turtle down (= the predicate-witness gap).
// ---------------------------------------------------------------------------

struct ClosureWitness {
    basis: ClosureBasis,
    signer: Signer,
    of_subject: Sha256, // must bind to the attestation subject
}

#[derive(Debug)]
enum ClosureBasis {
    HermeticBuild { builder_digest: Sha256 },
    // HumanContract { contract_digest: Sha256 }, // a human asserting closure is
    //   itself a witness and carries its own schema-checked, digest-bound contract.
}

// ---------------------------------------------------------------------------
// resolutions — the typed refusal surface.
// ---------------------------------------------------------------------------

#[must_use = "a dropped Resolution silently converts a claim into nothing"]
#[derive(Debug)] // note: intentionally NOT PartialEq and NOT Default
enum Resolution {
    Admissible,
    Inadmissible {
        component: ComponentId,
    },
    /// We make NO claim. This is not "not admissible" — it is unresolved, and it
    /// MUST NOT be read as clearance. There is no path that yields `Admissible`
    /// from this variant.
    Refused(RefusalReason),
}

#[derive(Debug)]
enum RefusalReason {
    /// The attestation is about a different artifact than the one in hand.
    BindingMismatch { expected: Sha256, got: Sha256 },
    /// The queried component lies outside boundary B.
    OutOfBoundary { component: ComponentId },
    /// A whole-artifact (completeness) claim with no closure witness.
    NoClosureWitness,
    /// A closure witness was supplied but does not bind to this subject.
    WitnessSubjectMismatch,
}

impl LicenseOriginAttestation {
    /// signed is not witnessed. The caller passes the digest it computed over the
    /// artifact *actually in hand*; we compare. No match → the attestation speaks
    /// of something else and witnesses nothing here.
    fn verify_binding(&self, artifact_in_hand: &Sha256) -> Result<(), RefusalReason> {
        if &self.subject == artifact_in_hand {
            Ok(())
        } else {
            Err(RefusalReason::BindingMismatch {
                expected: self.subject.clone(),
                got: artifact_in_hand.clone(),
            })
        }
    }

    /// Downstream check for ONE component. Out-of-boundary → `Refused`, never `Pass`.
    fn resolve_component(&self, artifact_in_hand: &Sha256, c: &ComponentId) -> Resolution {
        if let Err(r) = self.verify_binding(artifact_in_hand) {
            return Resolution::Refused(r);
        }
        match self.coverage.examined.get(c) {
            Some(Verdict::Pass) => Resolution::Admissible,
            Some(Verdict::Fail) => Resolution::Inadmissible { component: c.clone() },
            None => Resolution::Refused(RefusalReason::OutOfBoundary { component: c.clone() }),
        }
    }

    /// The dangerous query: "is the WHOLE artifact cleared?" A completeness claim.
    /// It cannot be satisfied from coverage alone — that would be deriving clearance
    /// from absence of findings (No Negative Clearance). It requires a closure
    /// witness binding to this subject. Even with one, every examined component
    /// must pass.
    fn resolve_whole_artifact(
        &self,
        artifact_in_hand: &Sha256,
        witness: Option<&ClosureWitness>,
    ) -> Resolution {
        if let Err(r) = self.verify_binding(artifact_in_hand) {
            return Resolution::Refused(r);
        }
        let witness = match witness {
            None => return Resolution::Refused(RefusalReason::NoClosureWitness),
            Some(w) => w,
        };
        if witness.of_subject != self.subject {
            return Resolution::Refused(RefusalReason::WitnessSubjectMismatch);
        }
        // Closure established. NOW and only now may "all examined pass" mean "whole."
        for (cid, v) in &self.coverage.examined {
            if *v == Verdict::Fail {
                return Resolution::Inadmissible { component: cid.clone() };
            }
        }
        Resolution::Admissible
    }
}

// ---------------------------------------------------------------------------
// the override seam — where "unknown" may become "proceed", but never silently
// and never as clearance.
// ---------------------------------------------------------------------------

/// To act past a refusal you must construct this. It records WHO accepted the
/// risk and WHY. In a full system this is the thing a Continuity log appends
/// (a claim receipt). It memorialises that you proceeded *despite* a refusal,
/// which is a strictly different fact from "the artifact was clear."
#[derive(Debug)]
struct RefusalOverride {
    refused: RefusalReason,
    accepted_by: Signer,
    justification: String,
}

impl RefusalOverride {
    fn record(refused: RefusalReason, accepted_by: Signer, justification: &str) -> Self {
        RefusalOverride {
            refused,
            accepted_by,
            justification: justification.to_string(),
        }
    }
}

#[derive(Debug)]
enum Decision {
    Proceed,
    ProceedUnderOverride(RefusalOverride),
    Halt,
}

/// The consumer's decision gate. Its TYPE is the guarantee: the only way to reach
/// a "go" from `Refused` is to supply a `RefusalOverride`. With no override, a
/// refusal becomes `Halt` — never `Proceed`. `Proceed` (clean go) is reachable
/// ONLY from `Admissible`.
///
/// KNOWN GAP (companion-note §gaps): this does NOT check that
/// `override_for_refusal.refused` matches `_reason`. A stricter version pattern-
/// matches the two so an override minted for reason X cannot wave through reason Y.
fn decide(resolution: Resolution, override_for_refusal: Option<RefusalOverride>) -> Decision {
    match resolution {
        Resolution::Admissible => Decision::Proceed,
        Resolution::Inadmissible { .. } => Decision::Halt,
        Resolution::Refused(_reason) => match override_for_refusal {
            // (a stricter version checks override.refused matches _reason)
            Some(ovr) => Decision::ProceedUnderOverride(ovr),
            None => Decision::Halt,
        },
    }
}

// ---------------------------------------------------------------------------
// what No Silent Conversion forbids — uncomment to watch it fail to compile.
// VERIFIED 2026-06-25: uncommenting yields error[E0369]: binary operation `==`
// cannot be applied to type `Resolution`.
// ---------------------------------------------------------------------------
//
// fn is_cleared(r: Resolution) -> bool {
//     r == Resolution::Admissible
//     // ERROR[E0369]: binary operation `==` cannot be applied to type `Resolution`
//     //   — and even if it could, this collapses Inadmissible and Refused into the
//     //   same `false`, silently reading "we make no claim" as "no". Refused that
//     //   means "we didn't look here" would become indistinguishable from a real
//     //   negative. The absence of PartialEq is the refusal of that collapse.
// }

fn main() {
    let artifact = Sha256("sha256:aaaa-artifact".into());
    let wrong_artifact = Sha256("sha256:bbbb-other".into());

    let mut examined = BTreeMap::new();
    examined.insert(ComponentId("pkg:cargo/serde@1.0".into()), Verdict::Pass);
    examined.insert(ComponentId("pkg:cargo/tokio@1.0".into()), Verdict::Pass);
    examined.insert(ComponentId("pkg:cargo/sketchy@0.1".into()), Verdict::Fail);

    let att = LicenseOriginAttestation {
        subject: artifact.clone(),
        policy: Sha256("sha256:policy-P".into()),
        coverage: Coverage { examined },
        signer: Signer("ci@example".into()),
    };

    let serde = ComponentId("pkg:cargo/serde@1.0".into());
    let sketchy = ComponentId("pkg:cargo/sketchy@0.1".into());
    let vendored = ComponentId("pkg:generic/vendored-blob".into()); // never examined

    println!("== single-component checks ==");
    println!("serde   (in B, pass): {:?}", att.resolve_component(&artifact, &serde));
    println!("sketchy (in B, fail): {:?}", att.resolve_component(&artifact, &sketchy));
    println!("vendored blob (∉ B):  {:?}", att.resolve_component(&artifact, &vendored));
    println!("  ^ the whole point: out-of-boundary REFUSES; it does not pass.\n");

    println!("== signed is not witnessed ==");
    println!("same attestation, wrong artifact: {:?}", att.resolve_component(&wrong_artifact, &serde));
    println!();

    println!("== completeness (the negative claim) ==");
    println!("whole artifact, NO closure witness: {:?}", att.resolve_whole_artifact(&artifact, None));
    println!("  ^ even setting aside the one failing component, absence-of-findings");
    println!("    outside B cannot be read as clear. No Negative Clearance.\n");

    let witness = ClosureWitness {
        basis: ClosureBasis::HermeticBuild { builder_digest: Sha256("sha256:builder-x".into()) },
        signer: Signer("buildsys@example".into()),
        of_subject: artifact.clone(),
    };
    println!("whole artifact, witness + failing component: {:?}",
        att.resolve_whole_artifact(&artifact, Some(&witness)));
    println!("  ^ closure now established, so the resolver may speak to the whole —");
    println!("    and it reports the real failure rather than refusing.\n");

    println!("== the override seam (No Silent Conversion) ==");
    println!("decide(refusal, no override):   {:?}", decide(att.resolve_component(&artifact, &vendored), None));
    let ovr = RefusalOverride::record(
        RefusalReason::OutOfBoundary { component: vendored.clone() },
        Signer("release-eng@example".into()),
        "vendored blob is first-party, tracked in TICKET-123; accepted for internal build",
    );
    println!("decide(refusal, recorded override): {:?}",
        decide(att.resolve_component(&artifact, &vendored), Some(ovr)));
    println!("  ^ proceeding is possible, but only as a named, recorded act — never a fall-through.\n");

    // doctrinal regression guards — the specimen fails loudly if any property erodes.
    assert!(
        matches!(att.resolve_component(&artifact, &vendored),
                 Resolution::Refused(RefusalReason::OutOfBoundary { .. })),
        "out-of-boundary MUST refuse, never clear"
    );
    assert!(
        matches!(att.resolve_whole_artifact(&artifact, None),
                 Resolution::Refused(RefusalReason::NoClosureWitness)),
        "completeness claim without closure witness MUST refuse"
    );
    assert!(
        matches!(decide(att.resolve_component(&artifact, &vendored), None), Decision::Halt),
        "refusal with no override MUST halt, never proceed"
    );
    assert!(
        matches!(decide(att.resolve_component(&artifact, &serde), None), Decision::Proceed),
        "in-boundary pass MUST proceed cleanly"
    );

    println!("all doctrinal assertions held.");
}
