#!/usr/bin/env python3
"""Generate docs/corpus.md — the public paper table — from preprint/*/metadata.yaml.

Usage: python3 tools/build_corpus_index.py [--check]

  (no args)  Regenerate docs/corpus.md in place.
  --check    Exit non-zero if docs/corpus.md is stale (for CI / pre-commit).

The corpus index is GENERATED. Do not hand-edit docs/corpus.md — edit the per-paper
metadata.yaml (the single source of truth the other tools already validate) and re-run
this script. Reuses the shared YAML loader and preprint discovery from zenodo_validate.

Deterministic: numbered papers first (by paper_number), then unnumbered series entries
(alphabetical by directory). No timestamps, so re-running on unchanged metadata is a no-op
diff — safe for a pre-commit staleness guard.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from zenodo_validate import find_preprint_dir, load_yaml_simple  # type: ignore

REPO_BLOB = "https://github.com/unpingable/papers/blob/main"
GENERATED_HEADER = (
    "<!-- GENERATED by tools/build_corpus_index.py — do not hand-edit. "
    "Edit preprint/<dir>/metadata.yaml and re-run. -->"
)
_NULLISH = {"", "null", "none", "~"}


def _clean(val: object) -> str:
    """Return a trimmed string, or '' for null-ish / missing values.

    Defensively strips a trailing inline YAML comment (` # ...`) and surrounding quotes,
    because the shared simple loader only strips full-line comments and only unquotes when
    a value both starts and ends with a quote. This keeps display clean when a metadata.yaml
    field carries a stray inline comment (seen in the wild: P12 `series`).
    """
    if val is None:
        return ""
    s = str(val).strip()
    s = re.sub(r"\s+#.*$", "", s).strip()  # drop inline comment tail
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", '"'):
        s = s[1:-1].strip()
    return "" if s.lower() in _NULLISH else s


def _iter_paper_dirs(preprint_dir: Path) -> list[Path]:
    dirs = [d for d in preprint_dir.iterdir() if d.is_dir() and (d / "metadata.yaml").exists()]

    def sort_key(d: Path) -> tuple[int, int, str]:
        m = re.match(r"^(\d+)-", d.name)
        if m:
            return (0, int(m.group(1)), d.name)  # numbered first, by number
        return (1, 0, d.name)  # unnumbered series entries after, alphabetical

    return sorted(dirs, key=sort_key)


def _row(meta: dict, dir_name: str) -> str:
    # Prefer the declared paper_number; fall back to the directory prefix (P01-P17 predate
    # the paper_number field). Unnumbered series entries (e.g. admissibility-kernels) → "—".
    num = _clean(meta.get("paper_number"))
    if not num.isdigit():
        m = re.match(r"^(\d+)-", dir_name)
        num = m.group(1) if m else ""
    ident = f"P{num.zfill(2)}" if num.isdigit() else "—"
    title = _clean(meta.get("title")) or dir_name
    title_link = f"[{_md_escape(title)}]({REPO_BLOB}/preprint/{dir_name}/)"
    series = _clean(meta.get("series")) or "—"
    version = _clean(meta.get("version")) or "—"
    date = _clean(meta.get("date")) or _clean(meta.get("last_updated")) or "—"
    doi = _clean(meta.get("doi"))
    if doi:
        published = f"[{doi}](https://doi.org/{doi})"
    else:
        published = "*source-ahead / unpublished*"
    return f"| {ident} | {title_link} | {series} | {version} | {date} | {published} |"


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def render() -> str:
    preprint_dir = find_preprint_dir()
    dirs = _iter_paper_dirs(preprint_dir)
    numbered = sum(1 for d in dirs if re.match(r"^\d+-", d.name))
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("# Corpus")
    lines.append("")
    lines.append(
        "Every paper in the corpus, generated from each paper's `metadata.yaml`. "
        "The table is the inventory; the [corpus map](map.md) is the conceptual order. "
        "Chronological number is **not** dependency order and **not** relative maturity — "
        "a higher number is newer, not stronger."
    )
    lines.append("")
    lines.append(
        f"**{len(dirs)} entries** ({numbered} in the Δt numbering, "
        f"{len(dirs) - numbered} standalone). *source-ahead / unpublished* means the repo "
        "source has no published DOI yet (draft or pending mint)."
    )
    lines.append("")
    lines.append("| # | Title | Series | Version | Date | Published |")
    lines.append("|---|-------|--------|---------|------|-----------|")
    for d in dirs:
        meta = load_yaml_simple(d / "metadata.yaml")
        lines.append(_row(meta, d.name))
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="Exit non-zero if docs/corpus.md is stale")
    args = ap.parse_args()

    out_path = find_preprint_dir().parent / "docs" / "corpus.md"
    new = render()

    if args.check:
        old = out_path.read_text() if out_path.exists() else ""
        if old != new:
            print(f"STALE: {out_path} does not match generated output. Run: "
                  "python3 tools/build_corpus_index.py", file=sys.stderr)
            return 1
        print(f"ok: {out_path} is up to date.", file=sys.stderr)
        return 0

    out_path.write_text(new)
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
